package visao;

import controle.Controle;

/**
 *
 * @author Usuário
 */
public class SenhaAtualGUI extends javax.swing.JFrame {

    private Controle controle;

    public SenhaAtualGUI(Controle controle) {
        initComponents();
        this.controle = controle;
        iniciarTela();

    }

    public void iniciarTela() {
        
        if (!controle.getSenhasPassadas().isEmpty()) {
            jLabelsenhaAtual.setText(controle.getSenhasPassadas().get(controle.getSenhasPassadas().size() - 1).getId());
        }
        if (controle.getSenhasPassadas().size() >= 2) {
            jLabelUltima1.setText(controle.getSenhasPassadas().get(controle.getSenhasPassadas().size() - 2).getId());
        }
        if (controle.getSenhasPassadas().size() >= 3) {
            jLabelUltima2.setText(controle.getSenhasPassadas().get(controle.getSenhasPassadas().size() - 3).getId());
        }
        if (controle.getSenhasPassadas().size() >= 4) {
            jLabelUltima3.setText(controle.getSenhasPassadas().get(controle.getSenhasPassadas().size() - 4).getId());
        }
        if (controle.getSenhasPassadas().size() >= 5) {
            jLabelUltima4.setText(controle.getSenhasPassadas().get(controle.getSenhasPassadas().size() - 5).getId());
        }
        if (controle.getSenhasPassadas().size() >= 6) {
            jLabelUltima5.setText(controle.getSenhasPassadas().get(controle.getSenhasPassadas().size() - 6).getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonChamar = new javax.swing.JButton();
        jButtonRetirar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelsenhaAtual = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelUltima1 = new javax.swing.JLabel();
        jLabelUltima2 = new javax.swing.JLabel();
        jLabelUltima3 = new javax.swing.JLabel();
        jLabelUltima4 = new javax.swing.JLabel();
        jLabelUltima5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonChamar.setText("Tela de chamada");
        jButtonChamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChamarActionPerformed(evt);
            }
        });

        jButtonRetirar.setText("Tela de retirada");
        jButtonRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Senha atual:");

        jLabelsenhaAtual.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabelsenhaAtual.setText("00");
        jLabelsenhaAtual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Últimas senhas chamadas:");

        jLabelUltima1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelUltima1.setText("00");
        jLabelUltima1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelUltima2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelUltima2.setText("00");
        jLabelUltima2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelUltima3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelUltima3.setText("00");
        jLabelUltima3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelUltima4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelUltima4.setText("00");
        jLabelUltima4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelUltima5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelUltima5.setText("00");
        jLabelUltima5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jButtonRetirar)
                        .addGap(111, 111, 111)
                        .addComponent(jButtonChamar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(97, 97, 97)
                                .addComponent(jLabelsenhaAtual))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabelUltima1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUltima2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelUltima3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelUltima4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelUltima5)))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelsenhaAtual))
                .addGap(74, 74, 74)
                .addComponent(jLabel3)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUltima1)
                    .addComponent(jLabelUltima2)
                    .addComponent(jLabelUltima3)
                    .addComponent(jLabelUltima4)
                    .addComponent(jLabelUltima5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRetirar)
                    .addComponent(jButtonChamar))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChamarActionPerformed
        // TODO add your handling code here:
        controle.abrirTelaChamarCliente();
        controle.fecharTelaSenhaAtual();
    }//GEN-LAST:event_jButtonChamarActionPerformed

    private void jButtonRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarActionPerformed
        // TODO add your handling code here:
        controle.abrirTelaDistribuirSenha();
        controle.fecharTelaSenhaAtual();
    }//GEN-LAST:event_jButtonRetirarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChamar;
    private javax.swing.JButton jButtonRetirar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelUltima1;
    private javax.swing.JLabel jLabelUltima2;
    private javax.swing.JLabel jLabelUltima3;
    private javax.swing.JLabel jLabelUltima4;
    private javax.swing.JLabel jLabelUltima5;
    private javax.swing.JLabel jLabelsenhaAtual;
    // End of variables declaration//GEN-END:variables
}
